/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_Ndk */

#ifndef _Included_com_example_test_Ndk
#define _Included_com_example_test_Ndk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_Ndk
 * Method:    getFun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_Ndk_getFun
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_Ndk
 * Method:    getHandle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_Ndk_getHandle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
